# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noodle < Formula
  desc "AI agent orchestration powered by skills"
  homepage "https://github.com/poteto/noodle"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poteto/noodle/releases/download/v0.1.1/noodle_darwin_amd64.tar.gz"
      sha256 "5f9a10e63e1c38c95e5cb520c98a27a67b1ee62e69dea2e27de774e5db212983"

      define_method(:install) do
        bin.install "noodle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poteto/noodle/releases/download/v0.1.1/noodle_darwin_arm64.tar.gz"
      sha256 "9a2f376103ea60cec0e3aaddc65bbae9a86af7495aabe88b106e897bc68befff"

      define_method(:install) do
        bin.install "noodle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poteto/noodle/releases/download/v0.1.1/noodle_linux_amd64.tar.gz"
      sha256 "205bc6f6e803280948974a8743369ef535ef66fb004a5eb1ee946217abe415bb"
      define_method(:install) do
        bin.install "noodle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poteto/noodle/releases/download/v0.1.1/noodle_linux_arm64.tar.gz"
      sha256 "0e8e88e7a85a9bb70b8f629ad1b112b60452b272878a888ac535884f96552506"
      define_method(:install) do
        bin.install "noodle"
      end
    end
  end
end
