# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noodle < Formula
  desc "Open-source AI coding framework"
  homepage "https://github.com/poteto/noodle"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poteto/noodle/releases/download/v0.1.0/noodle_darwin_amd64.tar.gz"
      sha256 "c7566744f7258dbe489d3597d7e4ac30b95feddc04f654e35e8d0dc874e68e58"

      define_method(:install) do
        bin.install "noodle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poteto/noodle/releases/download/v0.1.0/noodle_darwin_arm64.tar.gz"
      sha256 "ec65fffbedd2fb1bf2c2cb98eca8177f2dd187c2264c55a10e931da451e51d82"

      define_method(:install) do
        bin.install "noodle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poteto/noodle/releases/download/v0.1.0/noodle_linux_amd64.tar.gz"
      sha256 "44b100cc7faf8e0faf20338fbf86b2553f64e77b760be784dc7ef4534db32ced"
      define_method(:install) do
        bin.install "noodle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poteto/noodle/releases/download/v0.1.0/noodle_linux_arm64.tar.gz"
      sha256 "fbb4111732ab076b9b6253adf1711ec589535d2902c173e572236f93a9654459"
      define_method(:install) do
        bin.install "noodle"
      end
    end
  end
end
